# Generated by Django 5.2.7 on 2025-10-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('mode', models.CharField(choices=[('IN_CLINIC', 'In-Clinic Visit'), ('VIDEO_CALL', 'Video Call'), ('AUDIO_CALL', 'Audio Call')], default='IN_CLINIC', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.patient')),
            ],
        ),
    ]
