# Generated by Django 5.2.7 on 2025-10-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='affiliation',
            field=models.CharField(blank=True, help_text='e.g., Apollo Hospital, Indore', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_hours',
            field=models.CharField(blank=True, help_text='e.g., 10:00 AM - 06:00 PM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_modes',
            field=models.CharField(blank=True, help_text='e.g., In-person, Video', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Experience in years', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='e.g., Hindi, English', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Add each qualification on a new line.', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
