# Generated by Django 5.2.7 on 2025-10-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_doctor_affiliation_doctor_clinic_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_dps/'),
        ),
    ]
