# Generated by Django 5.2.7 on 2025-10-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_doctor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending Confirmation', 'Pending Confirmation'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending Confirmation', max_length=30),
        ),
    ]
