# Generated by Django 5.2.7 on 2025-10-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any known allergies', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='List any chronic diseases like Diabetes, Hypertension', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
